@apimName = <your-api-management-name>
@apiPath = customer
@id = 1234567890
@frontDoorGwEndpoint = <your-frontdoor-gateway-endpoint>
@subscriptionKeyConsumer = <your-consumer-subscription-key>

### Test Front door health check for API Management Gateway
GET https://{{frontDoorGwEndpoint}}/status-0123456789abcdef

### Test Azure API Management endpoint, with Consumer subscription key (should fail, 403)
GET https://{{apimName}}.azure-api.net/petstore/pet/findByStatus?status=available
api-key: {{subscriptionKeyConsumer}}

### Test Front Door endpoint, with Consumer subscription key (should succeed)
GET https://{{frontDoorGwEndpoint}}/petstore/pet/findByStatus?status=available
api-key: {{subscriptionKeyConsumer}}

### Customer API - Create
POST https://{{frontDoorGwEndpoint}}/{{apiPath}}
Content-Type: application/json
api-key: {{subscriptionKeyConsumer}}

{
    "id": "1234567890",
    "customerName": "John Doe",
    "customerEmail": "",
    "customerPhone": "1234567890",
    "customerAddress": {
        "street": "123 Main St",
        "city": "Anytown",
        "state": "CA",
        "zip": "12345"
    }
}

### Customer API - Delete
DELETE https://{{frontDoorGwEndpoint}}/{{apiPath}}/{{id}}
Content-Type: application/json
api-key: {{subscriptionKeyConsumer}}

### Customer API - Update
PUT https://{{frontDoorGwEndpoint}}/{{apiPath}}/{{id}}
Content-Type: application/json
api-key: {{subscriptionKeyConsumer}}

{
    "id": "1234567890",
    "customerName": "John Doe",
    "customerEmail": "",
    "customerPhone": "1234567890",
    "customerAddress": {
        "street": "123 Main St",
        "city": "Anytown",
        "state": "CA",
        "zip": "12345"
    }
}