openapi: 3.0.0
info:
  version: 1.0.0
  title: Customer API
paths:
  /customer:
    post:
      summary: Create a new customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
            example:
              customerId: "1234567890"
              customerName: "John Doe"
              customerEmail: "johndoe@example.com"
              customerPhone: "1234567890"
              customerAddress:
                street: "123 Main St"
                city: "Anytown"
                state: "CA"
                zip: "12345"
      responses:
        '201':
          description: Created
  /customer/{customerId}:
    put:
      summary: Update a customer by ID
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
            example:
              customerId: "1234567890"
              customerName: "Jane Doe"
              customerEmail: "janedoe@example.com"
              customerPhone: "0987654321"
              customerAddress:
                street: "456 Main St"
                city: "Anytown"
                state: "CA"
                zip: "54321"
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete a customer by ID
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted
components:
  schemas:
    Customer:
      type: object
      properties:
        customerId:
          type: string
        customerName:
          type: string
        customerEmail:
          type: string
        customerPhone:
          type: string
        customerAddress:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            state:
              type: string
            zip:
              type: string
      required:
        - customerId
        - customerName